"""add image_url to items

Revision ID: 552417e394f2
Revises: 3495fdc4b580
Create Date: 2026-08-02 00:01:27.028539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552417e394f2'
down_revision: Union[str, Sequence[str], None] = '3495fdc4b580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('items', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_column('items', 'image_url')
    # ### end Alembic commands ###
